Update sharepoint.yml

diff --git a/.github/workflows/sharepoint.yml b/.github/workflows/sharepoint.yml
--- a/.github/workflows/sharepoint.yml
+++ b/.github/workflows/sharepoint.yml
@@ -34,31 +34,32 @@ jobs:
           echo "Site ID:"
           echo "${{ env.site_id }}"
 
-    - name: Fetch download URL from SharePoint
+    - name: Fetch Download URL from SharePoint
       id: get_download_url
       run: |
-        file_response=$(curl -H "Authorization: Bearer ${{ env.token }}" \
-        "https://graph.microsoft.com/v1.0/sites/${{ env.site_id }}/drive/root:/env-uat")
-        echo "File response: $file_response"
-        download_url=$(echo $file_response | jq -r '.@microsoft.graph.downloadUrl')
-        echo "Download URL: $download_url"
-        echo "download_url=$download_url" >> $GITHUB_ENV
-    
+          file_response=$(curl -H "Authorization: Bearer ${{ env.token }}" \
+          "https://graph.microsoft.com/v1.0/sites/${{ env.site_id }}/drive/root:/${{ env.FILENAME }}")
+          echo "File response: $file_response"
+          download_url=$(echo $file_response | jq -r '."@microsoft.graph.downloadUrl"')
+          echo "Download URL: $download_url"
+          echo "download_url=$download_url" >> $GITHUB_ENV
+
     - name: Display Download URL
       run: |
-        echo "Download URL: ${{ env.download_url }}"
-    
-    - name: Download file from SharePoint
-      run: |
-        if [ -z "${{ env.download_url }}" ]; then
-          echo "Error: Download URL is empty"
-          exit 1
-        fi
-        curl -L "${{ env.download_url }}" --output fetched_file
-        echo "File downloaded successfully."
+          echo "Download URL:"
+          echo "${{ env.download_url }}"
 
-    - name: Upload fetched file as artifact
+    - name: Download File from SharePoint
+      run: |
+          if [ -z "${{ env.download_url }}" ]; then
+            echo "Error: Download URL is empty"
+            exit 1
+          fi
+          curl -L "${{ env.download_url }}" --output fetched_file
+          echo "File downloaded successfully."
+
+    - name: Upload Fetched File as Artifact
       uses: actions/upload-artifact@v3
       with:
-        name: fetched_file
-        path: fetched_file
+          name: fetched_file
+          path: fetched_file
